### ISSUE TITLE
Add A Beta Signup Form

### ISSUE THREAD

**Issue by jackspirou** [pixelprotection/pixelprotection.github.io#2]
As @lostphilosopher  suggested, lets add a beta signup form, or have the user complete the survey so then the can signup.

**Comment by lostphilosopher** [comment]
Hang on, I'm confused. My thought was  
1. They sign up for the newsletter.  
2. We invite them to participate in the Beta.  
3. Our invite sends them to app.pixelprotection.com/signup where they sign up with the flow you've already got in place (I'm assuming you're moving the application part of what was at pixelprotection.com to app.pixelprotection.com? Is that not the case?).  

Anyway, I'm not sure what you're looking for me to do with this...

**Comment by jackspirou** [comment]
I think your flow makes sense.

I just want to be clear about a beta signup vs a newsletter signup.  Do we need to have a clear distinction, or maybe both in one form is ok?  Thoughts?  Im open to either.

**Comment by jackspirou** [comment]
Im working on adding some style to the copy.  Nothing major, just trying to make it more readable.

Will be sending a pull request shortly...
