### ISSUE TITLE
Integrate click tracking to start collecting metrics

### ISSUE THREAD

**Issue by lostphilosopher** [pixelprotection/pixelprotection.github.io#4]
It would be good to know how many people are clicking some of the links we're providing, especially around subscribe, demo, and survey. Google Analytics is one way to do this, but there are others. GA does have the advantage of working well with Google Experiments which might be the next step? 

Thoughts?

**Comment by jackspirou** [comment]
I like GA, thats what we were working with before... I thought it was still on there via cloudflare... i'll check...

**Comment by jackspirou** [comment]
Done!
